/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TrafficLight {
        "next": () => Promise<void>;
        /**
          * @default 'stop'
         */
        "state": TrafficLightState;
    }
}
declare global {
    interface HTMLTrafficLightElement extends Components.TrafficLight, HTMLStencilElement {
    }
    var HTMLTrafficLightElement: {
        prototype: HTMLTrafficLightElement;
        new (): HTMLTrafficLightElement;
    };
    interface HTMLElementTagNameMap {
        "traffic-light": HTMLTrafficLightElement;
    }
}
declare namespace LocalJSX {
    interface TrafficLight {
        /**
          * @default 'stop'
         */
        "state"?: TrafficLightState;
    }

    interface TrafficLightAttributes {
        "state": TrafficLightState;
    }

    interface IntrinsicElements {
        "traffic-light": Omit<TrafficLight, keyof TrafficLightAttributes> & { [K in keyof TrafficLight & keyof TrafficLightAttributes]?: TrafficLight[K] } & { [K in keyof TrafficLight & keyof TrafficLightAttributes as `attr:${K}`]?: TrafficLightAttributes[K] } & { [K in keyof TrafficLight & keyof TrafficLightAttributes as `prop:${K}`]?: TrafficLight[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "traffic-light": LocalJSX.IntrinsicElements["traffic-light"] & JSXBase.HTMLAttributes<HTMLTrafficLightElement>;
        }
    }
}
