'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type RadioGroupCustomEvent, type SortableTableCustomEvent } from "my-components";
import { GoogleButton as GoogleButtonElement, defineCustomElement as defineGoogleButton } from "my-components/dist/components/google-button.js";
import { GoogleButton2 as GoogleButton2Element, defineCustomElement as defineGoogleButton2 } from "my-components/dist/components/google-button2.js";
import { HelloWorld as HelloWorldElement, defineCustomElement as defineHelloWorld } from "my-components/dist/components/hello-world.js";
import { RadioGroup as RadioGroupElement, defineCustomElement as defineRadioGroup } from "my-components/dist/components/radio-group.js";
import { ReactiveCss as ReactiveCssElement, defineCustomElement as defineReactiveCss } from "my-components/dist/components/reactive-css.js";
import { SortableTable as SortableTableElement, defineCustomElement as defineSortableTable } from "my-components/dist/components/sortable-table.js";
import React from 'react';

export type GoogleButtonEvents = NonNullable<unknown>;

export const GoogleButton: StencilReactComponent<GoogleButtonElement, GoogleButtonEvents> = /*@__PURE__*/ createComponent<GoogleButtonElement, GoogleButtonEvents>({
    tagName: 'google-button',
    elementClass: GoogleButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as GoogleButtonEvents,
    defineCustomElement: defineGoogleButton
});

export type GoogleButton2Events = NonNullable<unknown>;

export const GoogleButton2: StencilReactComponent<GoogleButton2Element, GoogleButton2Events> = /*@__PURE__*/ createComponent<GoogleButton2Element, GoogleButton2Events>({
    tagName: 'google-button2',
    elementClass: GoogleButton2Element,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as GoogleButton2Events,
    defineCustomElement: defineGoogleButton2
});

export type HelloWorldEvents = NonNullable<unknown>;

export const HelloWorld: StencilReactComponent<HelloWorldElement, HelloWorldEvents> = /*@__PURE__*/ createComponent<HelloWorldElement, HelloWorldEvents>({
    tagName: 'hello-world',
    elementClass: HelloWorldElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as HelloWorldEvents,
    defineCustomElement: defineHelloWorld
});

export type RadioGroupEvents = { onValueChanged: EventName<RadioGroupCustomEvent<string>> };

export const RadioGroup: StencilReactComponent<RadioGroupElement, RadioGroupEvents> = /*@__PURE__*/ createComponent<RadioGroupElement, RadioGroupEvents>({
    tagName: 'radio-group',
    elementClass: RadioGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onValueChanged: 'valueChanged' } as RadioGroupEvents,
    defineCustomElement: defineRadioGroup
});

export type ReactiveCssEvents = NonNullable<unknown>;

export const ReactiveCss: StencilReactComponent<ReactiveCssElement, ReactiveCssEvents> = /*@__PURE__*/ createComponent<ReactiveCssElement, ReactiveCssEvents>({
    tagName: 'reactive-css',
    elementClass: ReactiveCssElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as ReactiveCssEvents,
    defineCustomElement: defineReactiveCss
});

export type SortableTableEvents = { onTableSorted: EventName<SortableTableCustomEvent<SortDetail>> };

export const SortableTable: StencilReactComponent<SortableTableElement, SortableTableEvents> = /*@__PURE__*/ createComponent<SortableTableElement, SortableTableEvents>({
    tagName: 'sortable-table',
    elementClass: SortableTableElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onTableSorted: 'tableSorted' } as SortableTableEvents,
    defineCustomElement: defineSortableTable
});
