/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface HelloWorld {
    }
    interface LabeledInput {
        /**
          * @default ''
         */
        "id": string;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "name": string;
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLHelloWorldElement extends Components.HelloWorld, HTMLStencilElement {
    }
    var HTMLHelloWorldElement: {
        prototype: HTMLHelloWorldElement;
        new (): HTMLHelloWorldElement;
    };
    interface HTMLLabeledInputElement extends Components.LabeledInput, HTMLStencilElement {
    }
    var HTMLLabeledInputElement: {
        prototype: HTMLLabeledInputElement;
        new (): HTMLLabeledInputElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "hello-world": HTMLHelloWorldElement;
        "labeled-input": HTMLLabeledInputElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface HelloWorld {
    }
    interface LabeledInput {
        /**
          * @default ''
         */
        "id"?: string;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default ''
         */
        "name"?: string;
    }

    interface LabeledInputAttributes {
        "id": string;
        "label": string;
        "name": string;
    }

    interface IntrinsicElements {
        "app-root": AppRoot;
        "hello-world": HelloWorld;
        "labeled-input": Omit<LabeledInput, keyof LabeledInputAttributes> & { [K in keyof LabeledInput & keyof LabeledInputAttributes]?: LabeledInput[K] } & { [K in keyof LabeledInput & keyof LabeledInputAttributes as `attr:${K}`]?: LabeledInputAttributes[K] } & { [K in keyof LabeledInput & keyof LabeledInputAttributes as `prop:${K}`]?: LabeledInput[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.IntrinsicElements["app-root"] & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "hello-world": LocalJSX.IntrinsicElements["hello-world"] & JSXBase.HTMLAttributes<HTMLHelloWorldElement>;
            "labeled-input": LocalJSX.IntrinsicElements["labeled-input"] & JSXBase.HTMLAttributes<HTMLLabeledInputElement>;
        }
    }
}
