/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GoogleButton {
    }
    interface GoogleButton2 {
    }
    interface HelloWorld {
        /**
          * @default 'World'
         */
        "name": string;
    }
    interface RadioGroup {
        "labels": string;
        "legend": string;
        "name": string;
        "value": string;
        "values": string;
    }
    interface ReactiveCss {
    }
    interface SortableTable {
        /**
          * @default []
         */
        "data": LooseObject[];
        /**
          * @default false
         */
        "descending": boolean;
        "headings": string;
        "properties": string;
    }
}
export interface RadioGroupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRadioGroupElement;
}
export interface SortableTableCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSortableTableElement;
}
declare global {
    interface HTMLGoogleButtonElement extends Components.GoogleButton, HTMLStencilElement {
    }
    var HTMLGoogleButtonElement: {
        prototype: HTMLGoogleButtonElement;
        new (): HTMLGoogleButtonElement;
    };
    interface HTMLGoogleButton2Element extends Components.GoogleButton2, HTMLStencilElement {
    }
    var HTMLGoogleButton2Element: {
        prototype: HTMLGoogleButton2Element;
        new (): HTMLGoogleButton2Element;
    };
    interface HTMLHelloWorldElement extends Components.HelloWorld, HTMLStencilElement {
    }
    var HTMLHelloWorldElement: {
        prototype: HTMLHelloWorldElement;
        new (): HTMLHelloWorldElement;
    };
    interface HTMLRadioGroupElementEventMap {
        "valueChanged": string;
    }
    interface HTMLRadioGroupElement extends Components.RadioGroup, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRadioGroupElementEventMap>(type: K, listener: (this: HTMLRadioGroupElement, ev: RadioGroupCustomEvent<HTMLRadioGroupElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRadioGroupElementEventMap>(type: K, listener: (this: HTMLRadioGroupElement, ev: RadioGroupCustomEvent<HTMLRadioGroupElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRadioGroupElement: {
        prototype: HTMLRadioGroupElement;
        new (): HTMLRadioGroupElement;
    };
    interface HTMLReactiveCssElement extends Components.ReactiveCss, HTMLStencilElement {
    }
    var HTMLReactiveCssElement: {
        prototype: HTMLReactiveCssElement;
        new (): HTMLReactiveCssElement;
    };
    interface HTMLSortableTableElementEventMap {
        "tableSorted": SortDetail;
    }
    interface HTMLSortableTableElement extends Components.SortableTable, HTMLStencilElement {
        addEventListener<K extends keyof HTMLSortableTableElementEventMap>(type: K, listener: (this: HTMLSortableTableElement, ev: SortableTableCustomEvent<HTMLSortableTableElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLSortableTableElementEventMap>(type: K, listener: (this: HTMLSortableTableElement, ev: SortableTableCustomEvent<HTMLSortableTableElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLSortableTableElement: {
        prototype: HTMLSortableTableElement;
        new (): HTMLSortableTableElement;
    };
    interface HTMLElementTagNameMap {
        "google-button": HTMLGoogleButtonElement;
        "google-button2": HTMLGoogleButton2Element;
        "hello-world": HTMLHelloWorldElement;
        "radio-group": HTMLRadioGroupElement;
        "reactive-css": HTMLReactiveCssElement;
        "sortable-table": HTMLSortableTableElement;
    }
}
declare namespace LocalJSX {
    interface GoogleButton {
    }
    interface GoogleButton2 {
    }
    interface HelloWorld {
        /**
          * @default 'World'
         */
        "name"?: string;
    }
    interface RadioGroup {
        "labels"?: string;
        "legend"?: string;
        "name"?: string;
        "onValueChanged"?: (event: RadioGroupCustomEvent<string>) => void;
        "value"?: string;
        "values"?: string;
    }
    interface ReactiveCss {
    }
    interface SortableTable {
        /**
          * @default []
         */
        "data"?: LooseObject[];
        /**
          * @default false
         */
        "descending"?: boolean;
        "headings"?: string;
        "onTableSorted"?: (event: SortableTableCustomEvent<SortDetail>) => void;
        "properties"?: string;
    }

    interface HelloWorldAttributes {
        "name": string;
    }
    interface RadioGroupAttributes {
        "labels": string;
        "legend": string;
        "name": string;
        "value": string;
        "values": string;
    }
    interface SortableTableAttributes {
        "descending": boolean;
        "headings": string;
        "properties": string;
    }

    interface IntrinsicElements {
        "google-button": GoogleButton;
        "google-button2": GoogleButton2;
        "hello-world": Omit<HelloWorld, keyof HelloWorldAttributes> & { [K in keyof HelloWorld & keyof HelloWorldAttributes]?: HelloWorld[K] } & { [K in keyof HelloWorld & keyof HelloWorldAttributes as `attr:${K}`]?: HelloWorldAttributes[K] } & { [K in keyof HelloWorld & keyof HelloWorldAttributes as `prop:${K}`]?: HelloWorld[K] };
        "radio-group": Omit<RadioGroup, keyof RadioGroupAttributes> & { [K in keyof RadioGroup & keyof RadioGroupAttributes]?: RadioGroup[K] } & { [K in keyof RadioGroup & keyof RadioGroupAttributes as `attr:${K}`]?: RadioGroupAttributes[K] } & { [K in keyof RadioGroup & keyof RadioGroupAttributes as `prop:${K}`]?: RadioGroup[K] };
        "reactive-css": ReactiveCss;
        "sortable-table": Omit<SortableTable, keyof SortableTableAttributes> & { [K in keyof SortableTable & keyof SortableTableAttributes]?: SortableTable[K] } & { [K in keyof SortableTable & keyof SortableTableAttributes as `attr:${K}`]?: SortableTableAttributes[K] } & { [K in keyof SortableTable & keyof SortableTableAttributes as `prop:${K}`]?: SortableTable[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "google-button": LocalJSX.IntrinsicElements["google-button"] & JSXBase.HTMLAttributes<HTMLGoogleButtonElement>;
            "google-button2": LocalJSX.IntrinsicElements["google-button2"] & JSXBase.HTMLAttributes<HTMLGoogleButton2Element>;
            "hello-world": LocalJSX.IntrinsicElements["hello-world"] & JSXBase.HTMLAttributes<HTMLHelloWorldElement>;
            "radio-group": LocalJSX.IntrinsicElements["radio-group"] & JSXBase.HTMLAttributes<HTMLRadioGroupElement>;
            "reactive-css": LocalJSX.IntrinsicElements["reactive-css"] & JSXBase.HTMLAttributes<HTMLReactiveCssElement>;
            "sortable-table": LocalJSX.IntrinsicElements["sortable-table"] & JSXBase.HTMLAttributes<HTMLSortableTableElement>;
        }
    }
}
